### PR TITLE
Cost impact curves for IC8

### PR DESCRIPTION
**Pull request by MikaelaSmitGlobalFund**
Working with Tim to get the cost impact curves for IC8

### CODE REVIEW

**Comment by MikaelaSmitGlobalFund** [comment]
@tbhallett this pull request covers the latest changes and it looks like the tests are all working

**Comment by tbhallett** [comment]
> @tbhallett this pull request covers the latest changes and it looks like the tests are all working

So we should close #35 and #36 then...?

**Comment by tbhallett** [comment]
With merge in from `main`, we do indeed still have tests passing ✅, 

However, we have a failing test for the `test_ic7.py` -- due to a missing key `plhiv`.

If you know what this is due to, then push a fix.

Nevertheless, I'll use this branch as the base upon which to get the "Mehran figures" working.

**Comment by tbhallett** [comment]
@MikaelaSmitGlobalFund: The funding inside these scenarios files is quite different to how they are labelled: e.g. $12Bn scenario has total funding inside of $23Bn. This is probably the reason for approach a and b look the same.

**Comment by tbhallett** [comment]
Also - I've added a file with which to investigate the results, but it doesn't run due to a missing country 'SVR'...?

**Pull request closed without merging**
