### PR TITLE
Cleaning all the text and fix lives saved for TB

### PR DESCRIPTION
**Pull request by MikaelaSmitGlobalFund**

### CODE REVIEW

**Review by tbhallett — APPROVED** [review]
Very nice cleaning up

**Comment by tbhallett** [comment]
@MikaelaSmitGlobalFund --  could you just confirm that `test_ic8` still passes with these changes to computations for TB in report?

**Comment by MikaelaSmitGlobalFund** [comment]
Will test before cob - I need to update the ic8 key stats with the updates to the lives saved. I am just trying to soft code this change now. 

Will committ all of that. My apologies for making the pull request prior to fixing that check first.

**Comment by tbhallett** [comment]
[like]  Hallett, Timothy B reacted to your message:
________________________________

**Comment by tbhallett** [comment]
- [X] `test_ic8.py` passing

**Review by tbhallett — APPROVED** [review]

**Comment by MikaelaSmitGlobalFund** [comment]
[heart]         Mikaela Smit reacted to your message:
________________________________

**Pull request merged**
